# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: nice_nano_v2
    shield: settings_reset

  # Default: No dongle left hand side is the central and right is peripheral
  # Comment out and uncomment below for dongle mode
  - board: nice_nano_v2
    shield: kurnikas-split-lp-left-central

  # Default: Nice nano based dongle - left and right peripheral parts
  # - board: nice_nano_v2
  #   shield: kurnikas-split-lp-dongle
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_BUILD_OUTPUT_UF2=y
  # - board: nice_nano_v2
  #   shield: kurnikas-split-lp-left-peripheral
  
  - board: nice_nano_v2
    shield: kurnikas-split-lp-right
